<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Tomlyn" Version="2.10.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tqc.Build\Tqc.Build.csproj" />
    </ItemGroup>

</Project>
